name: Publish Package 'Data'

on:
  push:
    branches: [master]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build & Publish

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@ortsarchiv-gemeinlebarn'
        
      - name: Install Angular [npm install -g @angular/cli]
        run: npm install -g @angular/cli
        
      - name: Install Dependancies [npm ci]
        run: npm ci
        
      - name: Build Angular Library 'Data' [npm run ci:build]
        run: npm run ci:build:data          

      - name: Publish '@ortsarchiv-gemeinlebarn/data' Package [npm publish]
        run: npm publish ./dist/data --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_JS_TOKEN }}