name: Publish Package

on:
  push:
    branches: [master]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build & Publish

    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@ortsarchiv-gemeinlebarn'
        
      - name: Install Dependancies [npm ci]
        run: npm ci
        
      - name: Build Angular Library [npm run ci:build]
        run: npm run ci:build

      - name: Publish '@ortsarchiv-gemeinlebarn/data' Package [npm publish]
        run: npm publish ./dist/data
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}